include:
  - project: 'devops/gitlab-ci-templates'
    ref: master
    file: 'build-image.template.yaml'
  - project: 'devops/gitlab-ci-templates'
    ref: master
    file: 'helm.template.yaml'

default:
  tags:
    - adcorn-dev

variables:
  APP_NAME: "app"
  APP_NAMESPACE: "${CI_PROJECT_ROOT_NAMESPACE}-${CI_PROJECT_NAME}"
  ENVIRONMENT: dev

stages:
  - build
  - deploy

build:app:
  stage: build
  variables:
    APP_NAME: "app"
  extends: .build_image
  rules:
    - if: $CI_COMMIT_REF_NAME == "master"
      variables:
        BUILD_ARGS: "--build-arg NODE_ENV=development"
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH'

build:nginx:
  stage: build
  variables:
    APP_NAME: "nginx"
  extends: .build_image
  rules:
    - if: $CI_COMMIT_REF_NAME == "master"
      variables:
        BUILD_ARGS: "--build-arg NODE_ENV=development"
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH'

deploy:
  extends: .helm_upgrade
  stage: deploy
  rules:
    - if: $CI_COMMIT_REF_NAME == "master"
      variables:
        CONFIG: $DEV_CONFIG
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - if: '$CI_COMMIT_REF_NAME == "master" || $CI_COMMIT_REF_NAME == "release"'
